"""Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
 four million, find the sum of the even-valued terms.
"""
from utils import measure_execution_time


def main():
    limit = 4_000_000
    with measure_execution_time():
        even_fibonacci = (n for n in fibonacci_sequence(limit) if is_even(n))
        result = sum(even_fibonacci)
    print("Problem 2")
    print(f"The sum of all even fibonacci numbers below {limit} = {result}")


def fibonacci_sequence(limit):
    a, b = 1, 2
    while a <= limit:
        yield a
        a, b = b, a + b


def is_even(n):
    return n % 2 == 0


if __name__ == '__main__':
    main()
